dist: trusty
language: php

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - docker

before_script: 
  - composer install
  - docker/start.sh
  - docker/import_db.sh
  - docker/set_correct_permissions.sh

script:
  - vendor/bin/phpunit
  - docker/tests.sh

notifications:
  email: false
