dist: trusty
language: php

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - docker

before_script: 
  - composer install
  - cd docker
  - ./start.sh
  - ./import_db.sh
  - ./set_correct_permissions.sh

script:
  - vendor/bin/phpunit
  - cd docker
  - ./tests.sh
